#include "host_test.h"
#include "actuation_coordinator.h"
#include "robot_control_endpoint_adapter.h"
#include "robot_profile.h"
#include <string.h>
typedef struct {int speed_calls,stop_calls,fail_speed,fail_stop;uint8_t motor;int16_t rpm;} fake_t;
static int fs(void*c,uint8_t m,int16_t r){fake_t*f=c;f->speed_calls++;f->motor=m;f->rpm=r;return f->fail_speed;}
static int ft(void*c,uint8_t m){fake_t*f=c;f->stop_calls++;f->motor=m;return f->fail_stop;}
static bool make(robot_control_endpoint_adapter_t*a,fake_t*f,uint16_t id,uint8_t m){HOST_TEST_CHECK(robot_control_endpoint_adapter_init(a,f,m,id,"traction",ROBOT_ENDPOINT_REQUIRED,-15,15,fs,ft));return true;}
static bool capabilities(void){fake_t f={0};robot_control_endpoint_adapter_t a;HOST_TEST_CHECK(make(&a,&f,1,3));HOST_TEST_CHECK((ROBOT_CAP_OK) == (robot_velocity_set_rpm(&a.endpoint,12)));HOST_TEST_CHECK((3) == (f.motor));HOST_TEST_CHECK((12) == (f.rpm));HOST_TEST_CHECK((ROBOT_CAP_OUT_OF_RANGE) == (robot_velocity_set_rpm(&a.endpoint,16)));a.endpoint.available=false;HOST_TEST_CHECK((ROBOT_CAP_UNAVAILABLE) == (robot_velocity_set_rpm(&a.endpoint,1)));a.endpoint.available=true;a.endpoint.capabilities=0;HOST_TEST_CHECK((ROBOT_CAP_UNSUPPORTED) == (robot_velocity_set_rpm(&a.endpoint,1)));a.endpoint.capabilities=3;a.velocity.context=0;HOST_TEST_CHECK((ROBOT_CAP_INVALID_ARGUMENT) == (robot_velocity_set_rpm(&a.endpoint,1)));return true;}
static bool registry(void){robot_endpoint_registry_t r;robot_endpoint_registry_init(&r);fake_t f[ROBOT_ENDPOINT_REGISTRY_MAX+1]={0};robot_control_endpoint_adapter_t a[ROBOT_ENDPOINT_REGISTRY_MAX+1];for(size_t i=0;i<ROBOT_ENDPOINT_REGISTRY_MAX;i++){HOST_TEST_CHECK(make(&a[i],&f[i],i+1,i));HOST_TEST_CHECK((ROBOT_REGISTRY_OK) == (robot_endpoint_registry_add(&r,&a[i].endpoint)));}HOST_TEST_CHECK(robot_endpoint_registry_find(&r,2)==&a[1].endpoint);HOST_TEST_CHECK(robot_endpoint_registry_find(&r,99)==NULL);HOST_TEST_CHECK(robot_endpoint_registry_at(&r,0)!=NULL);HOST_TEST_CHECK(robot_endpoint_has_capability(&a[0].endpoint,ROBOT_CAPABILITY_STOPPABLE));HOST_TEST_CHECK((ROBOT_REGISTRY_DUPLICATE_ID) == (robot_endpoint_registry_add(&r,&a[0].endpoint)));HOST_TEST_CHECK(make(&a[ROBOT_ENDPOINT_REGISTRY_MAX],&f[ROBOT_ENDPOINT_REGISTRY_MAX],99,0));HOST_TEST_CHECK((ROBOT_REGISTRY_FULL) == (robot_endpoint_registry_add(&r,&a[ROBOT_ENDPOINT_REGISTRY_MAX].endpoint)));robot_endpoint_registry_init(&r);a[0].endpoint.capabilities=ROBOT_CAPABILITY_VELOCITY_RPM;a[0].endpoint.stoppable=&a[0].stoppable;HOST_TEST_CHECK((ROBOT_REGISTRY_CAPABILITY_MISMATCH) == (robot_endpoint_registry_add(&r,&a[0].endpoint)));return true;}
static bool profile(void){HOST_TEST_CHECK((ROBOT_PROFILE_VALID) == (robot_profile_validate(robot_profile_current())));robot_profile_t p=*robot_profile_current();p.schema_version=9;HOST_TEST_CHECK((ROBOT_PROFILE_BAD_SCHEMA) == (robot_profile_validate(&p)));p=*robot_profile_current();p.endpoints[1].id=p.endpoints[0].id;HOST_TEST_CHECK((ROBOT_PROFILE_DUPLICATE_ID) == (robot_profile_validate(&p)));p=*robot_profile_current();p.endpoints[0].drive_index=3;HOST_TEST_CHECK((ROBOT_PROFILE_BAD_REFERENCE) == (robot_profile_validate(&p)));p=*robot_profile_current();p.endpoints[0].channel=2;HOST_TEST_CHECK((ROBOT_PROFILE_BAD_CHANNEL) == (robot_profile_validate(&p)));p=*robot_profile_current();p.rc_rx_pin=p.rs485.tx_pin;HOST_TEST_CHECK((ROBOT_PROFILE_PIN_CONFLICT) == (robot_profile_validate(&p)));p=*robot_profile_current();p.endpoints[0].max_rpm=20;HOST_TEST_CHECK((ROBOT_PROFILE_BAD_LIMIT) == (robot_profile_validate(&p)));p=*robot_profile_current();p.endpoints[0].capabilities=ROBOT_CAPABILITY_STOPPABLE;HOST_TEST_CHECK((ROBOT_PROFILE_BAD_CAPABILITY) == (robot_profile_validate(&p)));return true;}
static bool coordinator(void){fake_t f[3]={0};robot_control_endpoint_adapter_t a[3];robot_endpoint_registry_t r;robot_endpoint_registry_init(&r);for(int i=0;i<3;i++){HOST_TEST_CHECK(make(&a[i],&f[i],i+1,i));HOST_TEST_CHECK((ROBOT_REGISTRY_OK) == (robot_endpoint_registry_add(&r,&a[i].endpoint)));}actuation_coordinator_t c;actuation_coordinator_init(&c,&r);actuation_report_t out;HOST_TEST_CHECK((ACTUATION_RESULT_SUCCESS) == (actuation_coordinator_set_velocity_rpm(&c,1,5,&out)));HOST_TEST_CHECK((1) == (out.applied));actuation_velocity_request_t q[]={{1,4},{2,5},{3,6}};HOST_TEST_CHECK((ACTUATION_RESULT_SUCCESS) == (actuation_coordinator_apply_velocity_rpm(&c,q,3,&out)));f[0].fail_speed=1;HOST_TEST_CHECK((ACTUATION_RESULT_FAILURE) == (actuation_coordinator_apply_velocity_rpm(&c,q,3,&out)));f[0].fail_speed=0;f[1].fail_speed=1;HOST_TEST_CHECK((ACTUATION_RESULT_PARTIAL) == (actuation_coordinator_apply_velocity_rpm(&c,q,3,&out)));HOST_TEST_CHECK(out.endpoints[0].rollback_stop_attempted);HOST_TEST_CHECK(f[0].stop_calls>0);f[1].fail_speed=0;HOST_TEST_CHECK((ACTUATION_RESULT_SUCCESS) == (actuation_coordinator_stop_all(&c,&out)));a[0].endpoint.capabilities=ROBOT_CAPABILITY_VELOCITY_RPM;HOST_TEST_CHECK((ACTUATION_RESULT_FAILURE) == (actuation_coordinator_stop_endpoint(&c,1,&out)));f[1].fail_stop=1;HOST_TEST_CHECK((ACTUATION_RESULT_PARTIAL) == (actuation_coordinator_stop_all(&c,&out)));return true;}
int main(void){const host_test_case_t t[]={{"capabilities",capabilities},{"registry",registry},{"profile",profile},{"coordinator",coordinator}};return host_test_exit_code(host_test_run_cases(t,HOST_TEST_ARRAY_COUNT(t),stderr));}
