// Generated by tools/analyze_as5600_linearity.py
// Calibration CSV SHA-256: a6a163ee94145694af91419be1c5a2224ecfbe34bd2299ea6cf3ed19f1bd743f
// Independently validated with CSV SHA-256: bb411066e975bbd558286d42eca9cbd5bbff71d930ec911e1470a90d1935ec59
//
//
// Each entry is a signed correction in centidegrees (0.01 degree), sampled
// every 32 raw AS5600 counts.  Interpolate cyclically between adjacent nodes.
// corrected_deg = raw * 360 / 4096 + interpolated_correction_centideg / 100.
// The complete 4096-count mapping was verified strictly monotonic.
#ifndef AS5600_LINEARITY_LUT_H
#define AS5600_LINEARITY_LUT_H

#include <stdint.h>

static constexpr uint16_t AS5600_LINEARITY_LUT_SIZE = 128;
static constexpr uint8_t AS5600_LINEARITY_COUNTS_PER_NODE = 32;
static constexpr float AS5600_LINEARITY_CENTIDEG_TO_DEG = 0.01f;

static constexpr int16_t AS5600_LINEARITY_LUT_CENTIDEG[AS5600_LINEARITY_LUT_SIZE] = {
     124,     58,     -9,    -77,   -147,   -218,   -290,   -364,
    -438,   -511,   -583,   -654,   -723,   -789,   -853,   -914,
    -972,  -1028,  -1081,  -1129,  -1173,  -1210,  -1241,  -1265,
   -1283,  -1295,  -1302,  -1304,  -1302,  -1293,  -1278,  -1257,
   -1231,  -1200,  -1165,  -1128,  -1087,  -1041,   -990,   -934,
    -875,   -815,   -754,   -692,   -630,   -569,   -510,   -455,
    -405,   -360,   -320,   -282,   -248,   -218,   -191,   -168,
    -148,   -128,   -109,    -89,    -69,    -49,    -30,    -12,
       7,     27,     50,     74,     99,    124,    149,    172,
     197,    223,    252,    283,    315,    346,    378,    409,
     443,    479,    518,    559,    602,    644,    686,    729,
     774,    820,    868,    915,    961,   1003,   1041,   1076,
    1108,   1135,   1157,   1174,   1184,   1188,   1186,   1178,
    1166,   1149,   1128,   1104,   1077,   1047,   1014,    979,
     941,    902,    860,    818,    774,    729,    684,    637,
     589,    538,    485,    430,    373,    313,    251,    188,
};

static inline float as5600LinearityCorrectionDeg(uint16_t rawAngle) {
  rawAngle &= 0x0FFFu;
  const uint8_t index = rawAngle >> 5;
  const uint8_t next = (index + 1u) & 0x7Fu;
  const float fraction = float(rawAngle & 0x1Fu) / 32.0f;
  const float a = float(AS5600_LINEARITY_LUT_CENTIDEG[index]);
  const float b = float(AS5600_LINEARITY_LUT_CENTIDEG[next]);
  return (a + (b - a) * fraction) * AS5600_LINEARITY_CENTIDEG_TO_DEG;
}

static inline float as5600CorrectedAngleDeg(uint16_t rawAngle) {
  float value = float(rawAngle & 0x0FFFu) * (360.0f / 4096.0f) +
                as5600LinearityCorrectionDeg(rawAngle);
  if (value < 0.0f) value += 360.0f;
  if (value >= 360.0f) value -= 360.0f;
  return value;
}

#endif  // AS5600_LINEARITY_LUT_H
